// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS9FuzTnhRYbCkMYDnthzyX7hIel7Jc-0',
    appId: '1:858864824848:android:418a9757727375a1081095',
    messagingSenderId: '858864824848',
    projectId: 'sakan-service-provider',
    storageBucket: 'sakan-service-provider.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWj5FVB428MaBe5_7Rd0icLFDxjjRyIOs',
    appId: '1:858864824848:ios:232f2b1755728410081095',
    messagingSenderId: '858864824848',
    projectId: 'sakan-service-provider',
    storageBucket: 'sakan-service-provider.firebasestorage.app',
    iosBundleId: 'com.sakan.service-provider',
  );

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDqbuXcafVDsudZYsQbMIP_Bfknro6Ofo8",
      appId: "1:858864824848:web:29a9e91ed840c23a081095",
      messagingSenderId: "858864824848",
      projectId: "sakan-service-provider",
      storageBucket: "sakan-service-provider.firebasestorage.app",
      measurementId: "G-Q6DRPYK1E5");
}
